### ISSUE TITLE
Delete method in role resource

### ISSUE THREAD

**Issue by CynthiaKamau** [mbbu/sample_management_system#10]
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column users.password does not exist
LINE 1: ...e AS users_last_name, users.email AS users_email, users.pass...

**Comment by jeffkim207** [comment]
I tested the role resource, I didn't encounter the said error. Did you fix it @CynthiaKamau? If so, you can close the issue.
